### ISSUE TITLE
Height option

### ISSUE THREAD

**Issue by Nazcain** [rominmx/postcss-compact-mq#1]
What about min-height and max-height?

**Comment by rominmx** [comment]
Sure! Will implement this feature in the next update.

**Comment by rominmx** [comment]
...done!
Check the `CHANGELOG` and `README`, there are a couple of new other features and (beware!) some incompability: commas now represent 'OR' operator, not 'AND' - like it was in version `0.1.0`.

**Comment by Nazcain** [comment]
Great!
